jobs:
  scheduled_task:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - run: ./example.sh
name: example
'on':
  schedule:
  - cron: 0 6 * * 1
  workflow_dispatch: null
