jobs:
  scheduled_task:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - run: ./example_dir/example.sh
    timeout-minutes: 5
name: Hello!
'on':
  schedule:
  - cron: 0 6 * * *
  workflow_dispatch: null
